### ISSUE TITLE
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.

### ISSUE THREAD

**Issue by dinager** [zappa/Zappa#1145] opened 2022-07-13 19:52 UTC
## Context

Getting the following error when running `zappa update dev`
(note: I havn't changed anything significant in my code since last deploy - which ran ok, just added a small `if` to my code, nd redeployed, but deploy fails)
```
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.
```
when I look in cloudwatch logs I see this error:
```
[ERROR] ModuleNotFoundError: No module named '_cffi_backend'
Traceback (most recent call last):
  File "/var/task/handler.py", line 657, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 251, in lambda_handler
    handler = cls()
  File "/var/task/handler.py", line 148, in __init__
    self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/app.py", line 6, in <module>
    from pusher_logic import push_to_pusher
  File "/var/task/pusher_logic.py", line 1, in <module>
    import pusher as pusher
  File "/var/task/pusher/__init__.py", line 3, in <module>
    from .pusher import Pusher
  File "/var/task/pusher/pusher.py", line 21, in <module>
    from pusher.pusher_client import PusherClient
  File "/var/task/pusher/pusher_client.py", line 32, in <module>
    from pusher.crypto import *
  File "/var/task/pusher/crypto.py", line 18, in <module>
    import nacl.secret
  File "/var/task/nacl/secret.py", line 17, in <module>
    import nacl.bindings
  File "/var/task/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_aead import (
  File "/var/task/nacl/bindings/crypto_aead.py", line 18, in <module>
    from nacl._sodium import ffi, lib
```
when I send a curl request to my lambda I get the following error response (again, I'll note: this worked well since the last deploy, and only since the recent deploy of today, things fail)

```
{
  "message": "An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.",
  "traceback": [
    "Traceback (most recent call last):\n",
    "  File '/var/task/handler.py', line 572, in handler\n    with Response.from_app(self.wsgi_app, environ) as response:\n",
    "  File '/var/task/werkzeug/wrappers/base_response.py', line 287, in from_app\n    return cls(*_run_wsgi_app(app, environ, buffered))\n",
    "  File '/var/task/werkzeug/wrappers/base_response.py', line 26, in _run_wsgi_app\n    return _run_wsgi_app(*args)\n",
    "  File '/var/task/werkzeug/test.py', line 1119, in run_wsgi_app\n    app_rv = app(environ, start_response)\n",
    "TypeError: 'NoneType' object is not callable\n"
  ]
}
```
I tried cleaning the venv and reinstall with  --no-cache-dir flag: `python -m pip install -r requirements.txt --no-cache-dir`, but did not help.

## Your Environment

* Zappa version used: `zappa==0.54.1`
* Operating System:  MacOs bigsur
* Python version: pyenv 3.7.10
* The output of `pip freeze`:
```
alembic==1.6.5
amqp==2.6.1
argcomplete==1.11.1
billiard==3.6.4.0
boto3==1.20.32
botocore==1.23.32
celery==4.4.7
certifi==2022.6.15
cffi==1.15.1
cfn-flip==1.2.3
chardet==3.0.4
click==7.1.2
cryptography==2.9.2
docutils==0.15.2
durationpy==0.5
Flask==1.1.2
Flask-Cors==3.0.10
Flask-Sockets==0.2.1
Flask-SQLAlchemy==2.4.4
future==0.18.2
gevent==20.5.0
gevent-websocket==0.10.1
greenlet==0.4.15
gunicorn==19.1.1
hjson==3.0.1
idna==2.9
importlib-metadata==1.6.0
itsdangerous==1.1.0
Jinja2==2.11.2
jmespath==0.10.0
kappa==0.6.0
kombu==4.6.11
logzio-python-handler==2.0.15
Mako==1.2.1
MarkupSafe==1.1.1
ndg-httpsclient==0.5.1
pip-tools==5.1.2
placebo==0.9.0
pusher==2.1.3
pyasn1==0.4.8
pycparser==2.20
PyJWT==1.7.1
PyMySQL==0.9.3
PyNaCl==1.3.0
pyOpenSSL==19.1.0
python-dateutil==2.6.1
python-editor==1.0.4
python-slugify==4.0.0
pytz==2022.1
PyYAML==5.3.1
requests==2.24.0
s3transfer==0.5.0
six==1.14.0
SQLAlchemy==1.3.20
SQLAlchemy-Utils==0.36.8
termcolor==1.1.0
text-unidecode==1.3
toml==0.10.1
tqdm==4.46.0
troposphere==3.0.0
typing-extensions==4.3.0
urllib3==1.25.9
vine==1.3.0
Werkzeug==0.16.1
wsgi-request-logger==0.4.6
zappa==0.54.1
zipp==3.1.0

```
* Your `zappa_settings.json`: 
```
{
    "dev": {
        "app_function": "app.app",
        "project_name": "my-cool-app",
        "runtime": "python3.7",
        "s3_bucket": "my-bucket",
        "aws_environment_variables" : {
            "MY_APP_ENV":"Base",
            "DB_SCHEMA":"my-db",
            "DB_PASS": "123456",
            "DB_USER": "aws_lambda",
            "DB_HOST":"my-host.cuploluxggsl.us-east-1.rds.amazonaws.com"
        },
        "profile_name": "zappa",
        "parameter_depth": 1,
        "apigateway_enabled": true,
        "certificate_arn": "arn:aws:acm:us-east-1:xxxxxxx:certificate/xxx-xxx-xx-xx-xxx",
        "domain": "my.domain.io",
        "route53_enabled": false
    }
}

```
my app.py:
```
import os
from flask import Flask, request
from flask_cors import cross_origin
from flask_sqlalchemy import SQLAlchemy
from service.log import get_logger, configure

server_env = os.environ.get("MYAPP_ENV", "Local")
app = Flask(__name__)
app.config.from_object("config.{server_env}".format(server_env=server_env))

db = SQLAlchemy(app)

configure()
_logger = get_logger(__name__)


@app.route('/process', methods=['POST'])
@cross_origin(supports_credentials=True)
def process():
    try:
        store_data_in_db(request.json)
    except Exception as e:
        _logger.exception(f"an exception occurred {e}")

    return 'ok'



if __name__ == '__main__':
    app.run()

```

**Comment by monkut** [comment] 2022-07-19 05:36
Common issue when your application is not configured or operating properly.

marking as a duplicate of:
https://github.com/zappa/Zappa/issues/382

closing.

**Closed by monkut** 2022-07-19 05:36 UTC
Labels: duplicate
