### ISSUE TITLE
[Migrated] Add Support for using an existing ALB and Listener

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#724] opened 2021-02-20 12:41 UTC
Originally from: https://github.com/Miserlou/Zappa/issues/1833 by [whahoo](https://github.com/whahoo)

## Description
I have been following along and using the ALB events and provisioning PR #1807  that was just merged in by @PeteW and @youcandanch.

I was using those changes and integrating my Lambda's into an existing ALB provisioned via terraform

I have some proposed zappa settings and code changes to allow the use of an existing ALB, multiple Zappa projects can then be deployed onto the same ALB

## GitHub Issues

#1832

**Comment by monkut** [comment] 2022-08-16 05:50
marking as duplicate of:
https://github.com/zappa/Zappa/issues/723

closing

**Closed by monkut** 2022-08-16 05:50 UTC
Labels: duplicate
