### ISSUE TITLE
For Private API, Not able to find option to mention VPC Endpoint Id in Zappa settings JSON file

### ISSUE THREAD

**Issue by mrsan22** [zappa/Zappa#1024] opened 2021-08-10 17:43 UTC
## Context
I am using Zappa to build and deploy a Flask Web application to AWS Lambda and API Gateway. My goal is to create a private API and have the API and Lambda under a VPC. 

I am able to find all the related property/attribute that we need (mentioned below in the Zappa settings JSON file) in order to create private API and Lambda function except a way to link `VPC Endpoint Id` to the API. After deployment, I had to go manually and add it under the API Gateway settings page.

Maybe this is not an issue and the option to provide `VPC Endpoint Id` is already there and it just me not able to find that option. Can someone pls guide me on this issue here?

I am running `Zappa 0.52` and `Python 3.7.4` in a virtualenv.

Thanks!

## Expected Behavior
Option to provide `VPCEndpoint ID` in Zappa Settings JSON file related to the API. The VPC Endpoint Id is related to this: [AWS Docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html)

When I provide the `VPCEndpoint ID` in Zappa Settings JSON file, it should update the API with this VPC Endpoint ID as shown below:
![Screen Shot 2021-08-10 at 1 37 51 PM](https://user-images.githubusercontent.com/7047364/128908304-b8fe73f5-4919-4965-b761-3296ca233017.png)

## Actual Behavior
This `VPC EndPoint ID` is left blank.

## My Environment

* Zappa version used: 0.52.0
* Operating System : macOS 10.14.6
* Python version: 3.7.4
* The output of `pip freeze`:
```
Package             Version
------------------- ---------
appdirs             1.4.4
argcomplete         1.12.2
astroid             2.4.2
attrs               20.3.0
Automat             20.2.0
blinker             1.4
boto3               1.16.59
botocore            1.19.59
certifi             2020.12.5
cfn-flip            1.2.3
chardet             4.0.0
click               7.1.2
constantly          15.1.0
coverage            5.3.1
durationpy          0.5
ecdsa               0.14.1
Flask               1.1.2
Flask-Cors          3.0.10
Flask-Mail          0.9.1
Flask-S3            0.3.3
Flask-Script        2.0.6
flask-sqlacodegen   1.1.8
Flask-SQLAlchemy    2.4.4
future              0.18.2
hjson               3.0.2
httpagentparser     1.9.1
idna                2.10
importlib-metadata  3.4.0
incremental         17.5.0
inflect             5.0.2
isort               5.7.0
itsdangerous        1.1.0
Jinja2              2.11.2
jmespath            0.10.0
kappa               0.6.0
lazy-object-proxy   1.4.3
Mako                1.1.4
MarkupSafe          1.1.1
mccabe              0.6.1
pip                 20.1
pip-tools           5.5.0
piwikapi            0.3
placebo             0.9.0
pyasn1              0.4.8
pycrypto            2.6.1
pylint              2.6.0
PyMySQL             1.0.2
python-dateutil     2.8.1
python-jose         3.2.0
python-slugify      4.0.1
PyYAML              5.4.1
requests            2.25.1
rsa                 4.7
s3transfer          0.3.4
setuptools          46.1.3
six                 1.15.0
SQLAlchemy          1.3.22
sqlparse            0.4.1
sqltap              0.3.11
text-unidecode      1.3
toml                0.10.2
tqdm                4.56.0
troposphere         2.6.3
typed-ast           1.4.2
typing-extensions   3.7.4.3
ujson               4.0.1
urllib3             1.26.2
Werkzeug            0.16.1
wheel               0.34.2
wrapt               1.12.1
wsgi-request-logger 0.4.6
zappa               0.52.0
zipp                3.4.0
zope.interface      5.2.0
```
* My `zappa_settings.json`: 
```
{
    "dev": {
        "app_function": "backend.wsgi_lambda.application",
        "aws_region": "us-east-1",
        "profile_name": "default",
        "project_name": "test-lambda",
        "runtime": "python3.7",
        "s3_bucket": "My_Bucket",
        "exclude": [
            "frontend*"
        ],
        "vpc_config": {
            "SubnetIds": ["subnet-1"],
            "SecurityGroupIds": [
                "sg-xxxx"
            ]
        },
        "endpoint_configuration": [
            "PRIVATE"
        ],
        "apigateway_policy": "apigateway_resource_policy.json"
    }
}
```

**Comment by suriya** [comment] 2021-08-14 02:22
Your question is great. Very well crafted and specifies exactly what the issue is.

The way to provide VPC Endpoint IDs in EndpointConfiguration is specified in the Cloudformation documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html

Zappa does not set the `VpcEndpointIds` field of the `EndpointConfiguration`
https://github.com/zappa/Zappa/blob/bb5834fa2f7c31f56cdc39fa883b96f9a99408e3/zappa/core.py#L1812

You will have to modify Zappa source and support it. It does not seem to be too difficult. You can maintain a fork of Zappa with these changes.

Question for Zappa Community. I am not sure who the "active" maintainers are. We are all duplicating effort maintaining different forks. Is there a proper mechanism for us to come together and review these changes and make them a part of Zappa master? I have 3 pull requests over the past 4 years that have never been merged and I keep maintaining them in my own fork. It is work for me to maintain them and neither does the community benefit. This is a lose-lose situation for others and me. I can volunteer time to maintain Zappa and merge the contributions into master.

**Comment by khuston** [comment] 2021-09-03 16:06
I also need this, so I will make a pull request shortly that will allow `endpoint_configuration` to be specified as a dict consistent with the [EndpointConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html) property. It'll have to be backwards compatible with providing the list of endpoint types as `endpoint_configuration` rather than as the `Types` property of it.

**Comment by mrsan22** [comment] 2021-11-18 00:48
Thanks for creating a PR for this issue @khuston.

**Closed** 2024-04-13 19:37 UTC
Labels: no-activity, auto-closed
