### ISSUE TITLE
[Migrated] QueryString encode issue with small fix 

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#836] opened 2021-02-20 12:52 UTC
Originally from: https://github.com/Miserlou/Zappa/issues/2077 by [ebertti](https://github.com/ebertti)

When the url has some querystring like:

`http://domain.com/path/to/view/?query=some%40mail.com` 

django wait to receive this:
```python
def some_view(request):
    query = request.GET.get('query')
    assert query == 'some@mail.com'
```
**with Zappa 0.51.0 and Django 3.0.5 and python 3.7 on Lambda and ALB**

this is the **actual behavior** 

```python
def some_view(request):
    query = request.GET.get('query')
    assert query == 'some%40mail.com'
```

So I made this small middleware to **quick fix**:

```python
class FixQueryStringZappaMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        if os.envirion('FRAMEWORK') == 'Zappa':
            querystring = request.GET.urlencode()
            u = urllib.parse.unquote(querystring)
            request.GET = QueryDict(u)
        response = self.get_response(request)
        return response
```
and add this middleware as first of your list of middlewares

this is my **zappa_settings.json**

```json
{
  "project": {
    "project_name": "project-backend",
    "aws_region": "sa-east-1",
    "alb_enabled": true,
    "apigateway_enabled": false,
    "cors": true,
    "keep_warm": false,
    "touch": false,
    "runtime": "python3.7",
    "timeout_seconds": 900,
    "log_level": "INFO",
    "s3_bucket": "some-bucket",
    "delete_s3_zip": false,
    "debug": true
  }
}
```

**Comment by john-parton** [comment] 2021-08-16 18:17
I think I'm experiencing a similar issue.

I think it might just be an ALB issue?

Wouldn't it be better to modify `ZappaWSGIMiddleware` to fix the encoding issue?

**Comment by monkut** [comment] 2022-07-16 05:48
considered a duplicate of
https://github.com/zappa/Zappa/issues/879

closing

**Closed by monkut** 2022-07-16 05:48 UTC
Labels: duplicate
