### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by joumaico** [zappa/Zappa#1274] opened 2023-09-14 13:14 UTC
**Python 3.11 support in the upcoming versions of Zappa.**

## Expected Behavior
As you can see in the settings, Lambda now supports Python 3.11 runtime.

![Screenshot from 2023-09-14 21-07-01](https://github.com/zappa/Zappa/assets/62525840/4f000b02-457e-4ae9-9ee9-4f4cd6925a7d)

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

## Actual Behavior

```
RuntimeError: This version of Python (3.11) is not supported!
Zappa (and AWS Lambda) support the following versions of Python: ['3.7', '3.8', '3.9', '3.10']
```

**Comment by monkut** [comment] 2023-09-19 14:25
0.58.0, supporting 3.11 was on 9/15, give it a try!

**Comment by monkut** [comment] 2023-09-19 14:26
marking as duplicate of the issue below and closing.
https://github.com/zappa/Zappa/issues/1262

**Closed by monkut** 2023-09-19 14:26 UTC
Labels: duplicate

**Comment by joumaico** [comment] 2023-09-19 19:27
> marking as duplicate of the issue below and closing. #1262

Thank you for the recent update.
