### ISSUE TITLE
[Migrated] request to change prints to logging or remove them

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#886] opened 2021-02-20 13:03 UTC
Originally from: https://github.com/Miserlou/Zappa/issues/2142 by [akobig](https://github.com/akobig)

Hi, I admire the zappa project and use it as my serverless platfrom. one thing that bugs me is the "Instancing.." print

zappa/handler.py
...
55 | print("Instancing..")
...

zappa/handler.py:
...
378 | print("Result of %s:" % whole_function)
379 | print(result)
...

I will appreciate removing or changing that line to debug log. tnx.

**Comment by monkut** [comment] 2022-07-16 05:25
I agree, logging should be used in place of print.

**Comment by monkut** [comment] 2022-10-29 01:21
marking as duplicate of:
https://github.com/zappa/Zappa/issues/677

**Closed by monkut** 2022-10-29 01:21 UTC
Labels: duplicate
