### ISSUE TITLE
TypeError: Object of type LambdaContext is not JSON serializable

### ISSUE THREAD

**Issue by hafneem** [zappa/Zappa#1149] opened 2022-07-15 18:09 UTC
[1657908474922] [ERROR] TypeError: Object of type LambdaContext is not JSON serializable
Traceback (most recent call last):
  File "/var/task/handler.py", line 657, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 254, in lambda_handler
    return handler.handler(event, context)
  File "/var/task/handler.py", line 392, in handler
    return self.run_function(app_function, event, context)
  File "/var/task/handler.py", line 295, in run_function
    result = app_function(event, context) if varargs else app_function()
  File "/var/task/zappa/asynchronous.py", line 445, in _run_async
    send_result = ASYNC_CLASSES[service](
  File "/var/task/zappa/asynchronous.py", line 182, in send
    self._send(message)
  File "/var/task/zappa/asynchronous.py", line 190, in _send
    payload = json.dumps(message)
  File "/var/lang/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/var/lang/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/var/lang/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/var/lang/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

Getting above error when invoking asynchronous task in django

**Comment by monkut** [comment] 2022-07-16 01:41
Async tasks require all arguments to be json serializable, as the task is passed to a new lambda context.

**Comment by hafneem** [comment] 2022-07-16 04:29
from zappa.asynchronous import task
from apps.youtube.models import YoutubeUser



@task
def zappa_task():
    """
    code block
    """


This is all what I'm doing in the function, no other arguments are being passed

**Comment by hafneem** [comment] 2022-07-16 04:31
Same as the below issue listed

https://github.com/zappa/Zappa/issues/425#issue-812552649

**Comment by monkut** [comment] 2022-07-19 05:30
marking as duplicate of
https://github.com/zappa/Zappa/issues/425#issue-812552649

closing.

**Closed by monkut** 2022-07-19 05:30 UTC
Labels: invalid
