### ISSUE TITLE
[Migrated] binary_support logic in handler.py (0.51.0) broke compressed text response

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#838] opened 2021-02-20 12:52 UTC
Originally from: https://github.com/Miserlou/Zappa/issues/2080 by [martinv13](https://github.com/martinv13)

## Context

The `binary_support` setting used to allow compressing response at application level (for instance using `flask_compress`) in version 0.50.0. As of 0.51.0 it no longer works.

## Expected Behavior

Compressed response using flask_compress should be possible.

## Actual Behavior

In `handler.py`, response is forced through `response.get_data(as_text=True)`, which fails for compressed payload, thus throwing an error. This is due to the modifications in #2029 which fixed a bug (previously all responses where base64 encoded), but introduced this one.

## Possible Fix

A possibility would be to partially revert to the previous version and just change in `handler.py` the "or" for a "and" in the following condition: `not response.mimetype.startswith("text/") or response.mimetype != "application/json")`. I can propose a simple PR for this.

## Steps to Reproduce
Configure Flask with flask_compress; any text or json response will fail with the following error: `'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

## Your Environment

* Zappa version used: 0.51.0
* Operating System and Python version: Python 3.7 on Lambda
* Your `zappa_settings.json`: relevant option: binary_support: true

**Comment by monkut** [comment] 2022-08-16 05:15
marking as a duplicate of the following and closing.
https://github.com/zappa/Zappa/issues/908

**Closed by monkut** 2022-08-16 05:15 UTC
Labels: duplicate
