### ISSUE TITLE
[Migrated] Remove single quotes in remote function invocation example in readme

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#901] opened 2021-02-20 13:03 UTC
Originally from: https://github.com/Miserlou/Zappa/issues/2163 by [LaundroMat](https://github.com/LaundroMat)

## Description
Do not use single quotes around application function when invoking remotely. 

## GitHub Issues
https://github.com/Miserlou/Zappa/issues/2162

**Comment by monkut** [comment] 2022-07-16 05:12
duplicate of https://github.com/zappa/Zappa/issues/900

closing

**Closed by monkut** 2022-07-16 05:12 UTC
Labels: duplicate
