### ISSUE TITLE
Python 3.12 is not supported

### ISSUE THREAD

**Issue by Esty12** [zappa/Zappa#1309] opened 2024-03-07 06:30 UTC
## Context
 I get an error when I try to run Zappa with the Python 3.12 version. Could Zappa please be updated to support Python 3.12?

## Actual Behavior

A RuntimeError occurs:

```
RuntimeError: This version of Python (3.12) is not supported!
Zappa (and AWS Lambda) support the following versions of Python: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.11']

```

## Steps to Reproduce

1. `python3 -m venv ./venv (on Python 3.12)`
2. `source venv/bin/activate`
3. `pip install zappa`
4. `zappa update [your_environment]`

## Your Environment

* Zappa version used: "0.58.0"
* Operating System and Python version: MacOS Python 3.12
* The output of `pip freeze`:
`argcomplete==3.2.2
blinker==1.7.0
boto3==1.34.57
botocore==1.34.57
certifi==2024.2.2
cfn-flip==1.3.0
charset-normalizer==3.3.2
click==8.1.7
durationpy==0.6
Flask==3.0.2
hjson==3.1.0
idna==3.6
itsdangerous==2.1.2
Jinja2==3.1.3
jmespath==1.0.1
kappa==0.6.0
MarkupSafe==2.1.5
placebo==0.9.0
python-dateutil==2.9.0.post0
python-slugify==8.0.4
PyYAML==6.0.1
requests==2.31.0
s3transfer==0.10.0
six==1.16.0
text-unidecode==1.3
toml==0.10.2
tqdm==4.66.2
troposphere==4.6.0
urllib3==2.0.7
Werkzeug==3.0.1
wheel==0.42.0
zappa==0.58.0
`

**Comment by javulticat** [comment] 2024-03-11 19:46
Duplicate of #1291

**Closed by javulticat** 2024-03-11 19:46 UTC
