### ISSUE TITLE
AttributeError: 'Template' object has no attribute 'add_description'

### ISSUE THREAD

**Issue by kazitanvirahsan** [zappa/Zappa#1002] opened 2021-07-08 11:40 UTC
<img width="1138" alt="Screen Shot 2021-07-08 at 9 38 01 pm" src="https://user-images.githubusercontent.com/6487015/124915500-f481ca80-e034-11eb-9cb7-766e139327aa.png">

Continuously getting this error while deploying basic flask application to AWS. Any help would be much appreciated.

**Comment by pulsedemon** [comment] 2021-07-08 23:36
I'm also getting this error on 0.52.0

**Comment by Raam124** [comment] 2021-07-09 01:31
I'm also getting this error

**Comment by xncbf** [comment] 2021-07-09 06:07
Same issue occurs. But update was done.

**Comment by kazitanvirahsan** [comment] 2021-07-09 14:52
Hai Guys,
I was able to bypass these issues. It has something to do with the troposphere for AWS cloud formation. 
pip3 install "troposphere==2.7.0"
References: https://github.com/zappa/Zappa/issues/1000

**Comment by ochilab** [comment] 2021-07-14 12:49
I also faced same issue, but avoided it due to kazitanvirahsan's solution.

**Comment by Puude** [comment] 2021-07-14 12:57
Same

**Comment by ian-whitestone** [comment] 2021-07-17 15:28
This is a duplicate of https://github.com/zappa/Zappa/issues/1000, can we close this one and keep discussion in there?

**Comment by monkut** [comment] 2022-07-16 04:45
https://github.com/zappa/Zappa/issues/1000
duplicate, closing.

**Closed by monkut** 2022-07-16 04:45 UTC
Labels: duplicate
