### ISSUE TITLE
Zappa shouldn't encode application/javascript into base64

### ISSUE THREAD

**Issue by tsuga** [zappa/Zappa#1021] opened 2021-08-08 03:16 UTC
## Context
Currently, minetypes starts with `text/` and `application/json` are handled as text responses from the WSGI server.

[zappa/handler.py#L585-L596](https://github.com/zappa/Zappa/blob/master/zappa/handler.py#L585-L596)
```python
if response.data:
    if (
        settings.BINARY_SUPPORT
        and not response.mimetype.startswith("text/")
        and response.mimetype != "application/json"
    ):
        zappa_returndict["body"] = base64.b64encode(
            response.data
        ).decode("utf-8")
        zappa_returndict["isBase64Encoded"] = True
    else:
        zappa_returndict["body"] = response.get_data(as_text=True)
```

## Expected Behavior
`application/json` should be returned as text.

## Actual Behavior

If `setting.BINARY_SUPPORT` is true, Zappa encodes it by base64.

## Possible Fix
Add `application/json` and other similar minetypes. I will create a PR shortly.

## Steps to Reproduce

omitted

## Your Environment

* Zappa version used: 0.53.0
* Operating System and Python version: Windows 10, Python 3.8.10
* The output of `pip freeze`: omitted
* Link to your project (optional): omitted
* Your `zappa_settings.json`: omitted

**Comment by monkut** [comment] 2022-07-16 02:00
marking as duplicate of
https://github.com/zappa/Zappa/issues/908

closing.

**Closed by monkut** 2022-07-16 02:00 UTC
Labels: duplicate
